### ISSUE TITLE
Instantiating Server Side Ziggeo Signature Changed

### ISSUE THREAD

**Issue by edmenendez** [Ziggeo/ZiggeoPythonSdk#20]
Currently the documentation says that the Server SDK is started like this:

> ziggeo = Ziggeo("*token*", "*private_key*", "*encryption_key*") 

[](https://github.com/Ziggeo/ZiggeoPythonSdk#server-side-integration)

However, it looks like in 2.8, the signature changed and encryption_key is no longer allowed. If you try to upgrade from 2.7 to 2.8 you will get errors like this

`Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/var/www/learn/src/py/community/management/commands/update_ziggeo.py", line 30, in handle
    settings.ZIGGEOAPI_ENCRYPTION_KEY,
  File "/usr/local/lib/python3.6/site-packages/Ziggeo.py", line 26, in __init__
    self.connect = ZiggeoConnect(self, server_api_url)
TypeError: __init__() takes 2 positional arguments but 3 were given`

Reverting back to 2.7 solved the problem.

**Comment by ibnutri** [comment]
Hi @edmenendez 

We have updated our pypi package to solve this issue, please update your library to get the update.

Thank you,
